package com.glsebastiany.smartcatalogspl.instanceditlanta.data.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.glsebastiany.smartcatalogspl.instanceditlanta.data.db.Category;
import com.glsebastiany.smartcatalogspl.instanceditlanta.data.db.Item;
import com.glsebastiany.smartcatalogspl.instanceditlanta.data.db.SuitCase;

import com.glsebastiany.smartcatalogspl.instanceditlanta.data.db.CategoryDao;
import com.glsebastiany.smartcatalogspl.instanceditlanta.data.db.ItemDao;
import com.glsebastiany.smartcatalogspl.instanceditlanta.data.db.SuitCaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig suitCaseDaoConfig;

    private final CategoryDao categoryDao;
    private final ItemDao itemDao;
    private final SuitCaseDao suitCaseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        suitCaseDaoConfig = daoConfigMap.get(SuitCaseDao.class).clone();
        suitCaseDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        suitCaseDao = new SuitCaseDao(suitCaseDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Item.class, itemDao);
        registerDao(SuitCase.class, suitCaseDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        suitCaseDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public SuitCaseDao getSuitCaseDao() {
        return suitCaseDao;
    }

}
