package com.glsebastiany.smartcatalogspl.instanceditlanta.data.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.glsebastiany.smartcatalogspl.core.data.CategoryGroupModel;
// KEEP INCLUDES END


/**
 * Entity mapped to table "SUIT_CASE".
 */
public class SuitCase implements CategoryGroupModel {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String imageUrl;
    /** Not-null value. */
    private String categoryList;
    private long order;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SuitCase() {
    }

    public SuitCase(Long id) {
        this.id = id;
    }

    public SuitCase(Long id, String name, String imageUrl, String categoryList, long order) {
        this.id = id;
        this.name = name;
        this.imageUrl = imageUrl;
        this.categoryList = categoryList;
        this.order = order;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getImageUrl() {
        return imageUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /** Not-null value. */
    public String getCategoryList() {
        return categoryList;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryList(String categoryList) {
        this.categoryList = categoryList;
    }

    public long getOrder() {
        return order;
    }

    public void setOrder(long order) {
        this.order = order;
    }

    // KEEP METHODS - put your custom methods here
    public String getStringId(){
        return id.toString();
    }
    // KEEP METHODS END

}
